### ISSUE TITLE
unable to build

### ISSUE THREAD

**Issue by Karlheinzniebuhr** [fboldog/AnkoMaterialSamples#2]
I always get this error, none of the named fixes does fix this issue

`Unable to find method 'com.android.build.gradle.internal.variant.BaseVariantData.getOutputs()Ljava/util/List;'.
Possible causes for this unexpected error include:<ul><li>Gradle's dependency cache may be corrupt (this sometimes occurs after a network connection timeout.)
Re-download dependencies and sync project (requires network)</li><li>The state of a Gradle build process (daemon) may be corrupt. Stopping all Gradle daemons may solve this problem.
Stop Gradle build processes (requires restart)</li><li>Your project may be using a third-party plugin which is not compatible with the other plugins in the project or the version of Gradle requested by the project.</li></ul>In the case of corrupt Gradle processes, you can also try closing the IDE and then killing all Java processes.
`

**Comment by fboldog** [comment]
I think your error wasn't project related. :(

However I did some updates to the project (gradle, kotlin, anko). 
Please check.
